### ISSUE TITLE
`listChildren` array elements have no `key`

### ISSUE THREAD

**Issue by mAAdhaTTah** [privatenumber/ink-task-list#2]
## Bug description
The `Task` component convert its non-array children into an array, but in doing so, doesn't provide a `key` to the element within, producing the following error:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Task`. It was passed a child from EnvSetup. See https://reactjs.org/link/warning-keys for more information.
    at Text (/[redacted]/cli/node_modules/ink/build/components/Text.js:12:17)
    in Task (created by EnvSetup)
    in ink-box (created by Box)
    in Box (created by TaskList)
    in TaskList (created by EnvSetup)
    in EnvSetup
    in InternalApp
```

## Reproduction steps
1. Pass `Task` a single element child + `isExpanded`.
2. Run `ink`.
3. See the above error.

## Environment

- ink-task-list version: 1.0.0
- Webpack version: Pastel
- Operating System: OSX
- Node version: 15.14.0
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.10

**Comment by privatenumber** [comment]
Works fine for me:
```
import React from 'react';
import { render } from 'ink';
import { Task } from 'ink-task-list';

render(
	<Task
		label="Label 1"
		isExpanded
	>
		<Task
			label="Label 2"
			state="loading"
		/>
	</Task>
);
```

Can you provide reproduction code?

**Comment by mAAdhaTTah** [comment]
Yeah, so I was creating children in a separate function (I'm using the expanded area to prompt questions about currently running tasks) and passed it as a prop, which caused it:

```js
<Task label="Label 1" isExpanded children={<Text>Label 2</Text>} />
```

(I used `Text` for simplicity but did repro initially with `Task` as well.)

It's a bit odd because both cases, the `children` comes into `Task` as an object, rather than an array, but I did notice this part of the message:

> Check the render method of `Task`. **It was passed a child from Hello.**

(emphasis mine)

which suggests (to me) that React is treating `children`  passed via JSX differently from `children` passed via prop.

This behavior also appears consistent between React 16 + 17.

FWIW, if no children are provided and you render the expanded box anyway, does it take up space? Alternatively, might be better to use the [`React.Children` methods](https://reactjs.org/docs/react-api.html#reactchildren) for this. I can open a PR for this.

**Comment by mAAdhaTTah** [comment]
Using `React.Children.toArray` instead of the current `Array.isArray` ternary resolved the issue for me locally.

**Comment by privatenumber** [comment]
Thanks for the details and fix.

Out of curiosity, what's the reasoning behind passing in children as a prop?

**Comment by privatenumber** [comment]
Ahh I see. Thanks for the explanation!
